@startuml birdie_system_architecture
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title "Birdie System Architecture"
left footer Alex Beacon | %date("yyyy-MM-dd") | v1.1

Person(user, "User")

System_Boundary(birdie_system, "Birdie System") {
    System(birdie, "Birdie\nApp", "React Native")
    SystemDb(birdie_db, "Birdie\nDatabase")
}

System_Boundary(internet, "Internet") {
    System(ebird, "eBird", "REST API")
    System(wiki, "iNaturalist")
}

Rel(user, birdie, "studies bird ID")
Rel_R(birdie, birdie_db, "load bird Flashcard data")
Rel(birdie_db, ebird, "get species data")
Rel(birdie_db, wiki, "get bird picture")

SHOW_LEGEND()

@enduml